# Shared secrets, generated by Terraform and stored in SSM SecureString. Both
# are consumed by the modules (passed as param name/arn), never as env vars.

# HMAC signing key for the approval tokens.
resource "random_password" "hmac" {
  length  = 48
  special = false
}

resource "aws_ssm_parameter" "hmac_secret" {
  name        = "/${var.name_prefix}/hmac-secret"
  description = "HMAC key signing Sentinel approval tokens"
  type        = "SecureString"
  value       = random_password.hmac.result
}

# Bearer token gating the dashboard read API.
resource "random_password" "dashboard_token" {
  length  = 40
  special = false
}

resource "aws_ssm_parameter" "dashboard_token" {
  name        = "/${var.name_prefix}/dashboard-token"
  description = "Bearer token gating the Sentinel dashboard read API"
  type        = "SecureString"
  value       = random_password.dashboard_token.result
}
